apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mysql-pvc
   namespace: wow-wotlk-trinitycore
   annotations:
     volume.beta.kubernetes.io/storage-class: default
spec:
   accessModes:
     - ReadWriteMany
   resources:
     requests:
       storage: 20Gi