apiVersion: v1
kind: Service
metadata:
  name: wotlk-mysql-service
  namespace: wow-wotlk-trinitycore
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  type: LoadBalancer